import React, { useEffect, useMemo, useState } from "react";
import { Mail, CalendarDays, BedDouble, MessageCircle, UserRound, BellRing, CheckCircle2, ShieldCheck } from "lucide-react";
import { api } from "../api";
import { useAuth, useToast } from "../state";
import { prettyDate } from "../utils";
import PageHero from "../components/PageHero";

const icons = { appointment: CalendarDays, ward: BedDouble, message: MessageCircle, account: UserRound, support: ShieldCheck, test: Mail };

export default function Alerts() {
  const { user } = useAuth();
  const { push } = useToast();
  const [emails, setEmails] = useState([]);
  const [filter, setFilter] = useState("all");
  const load = () => { const path = user.role === "admin" ? "/admin/emails" : `/emails/${user.id}`; api(path).then(setEmails); };
  useEffect(() => { load(); }, [user.id, user.role]);
  const test = async () => { await api("/emails/test", { method: "POST", body: JSON.stringify({ userId: user.id }) }); push("Test notice sent"); load(); };
  const rows = emails.filter((e) => filter === "all" || e.type === filter);
  const delivered = useMemo(() => emails.filter((e) => ["delivered", "sent"].includes(e.status)).length, [emails]);
  const categories = useMemo(() => new Set(emails.map((e) => e.type)).size, [emails]);

  return <div className="notices-os">
    <PageHero scene="alerts" eyebrow={user.role === "admin" ? "Communication audit" : "Hospital communication"} title={user.role === "admin" ? "Patient notices" : "Notification centre"} lead={user.role === "admin" ? "Review the confirmations and service notices generated by CareBridge across patient workflows." : "A single timeline for appointment confirmations, admission decisions, account notices and care-team communication."} actions={user.role === "patient" ? <button className="primary-btn" onClick={test}><Mail size={16} /> Test my notices</button> : null} />

    <section className="ops-metric-grid notice-kpis">
      <article className="ops-metric"><span className="ops-metric-icon"><BellRing size={17} /></span><div><small>Total notices</small><strong>{emails.length}</strong><em>Your communication history</em></div></article>
      <article className="ops-metric"><span className="ops-metric-icon green"><CheckCircle2 size={17} /></span><div><small>Delivered</small><strong>{delivered}</strong><em>Successfully posted</em></div></article>
      <article className="ops-metric"><span className="ops-metric-icon blue"><Mail size={17} /></span><div><small>Categories</small><strong>{categories}</strong><em>Workflow sources</em></div></article>
      <article className="ops-metric"><span className="ops-metric-icon amber"><ShieldCheck size={17} /></span><div><small>Channel</small><strong>Email</strong><em>Hospital notice log</em></div></article>
    </section>

    <section className="product-section notice-centre-panel">
      <div className="notice-centre-toolbar"><div><span className="eyebrow">Notice timeline</span><h3>{user.role === "admin" ? "Generated patient communication" : "Your hospital communication"}</h3></div><div className="directory-role-tabs">{["all", "appointment", "ward", "message", "account", "support", "test"].map((t) => <button key={t} className={filter === t ? "active" : ""} onClick={() => setFilter(t)}>{t === "all" ? "All" : t[0].toUpperCase() + t.slice(1)}</button>)}</div></div>
      <div className="notice-timeline">
        {rows.map((e) => { const Icon = icons[e.type] || Mail; return <article className="notice-record" key={e.id}><span className="notice-record-icon"><Icon size={16} /></span><div className="notice-record-body"><div><span className="eyebrow">{e.type || "notice"}</span><strong>{e.subject}</strong></div><p>{e.text}</p><small>To {e.to} · {prettyDate(e.sentAt)}</small></div><div className="notice-record-state"><span className={`status ${e.status}`}>{e.status}</span>{e.previewUrl && <a className="ghost-btn" href={e.previewUrl} target="_blank" rel="noreferrer">Preview</a>}</div></article>; })}
        {rows.length === 0 && <div className="product-empty-inline"><Mail size={18} /><span>No notices match this view.</span></div>}
      </div>
    </section>
  </div>;
}
